export const LOAD_ABOUT_PAGE_DATA = 'LOAD_ABOUT_PAGE_DATA';
export const FETCH_ABOUT_PAGE_DATA = 'FETCH_ABOUT_PAGE_DATA';

export const USER_INIT = 'USER_INIT';
export const USER_SIGNUP = 'USER_SIGNUP';
export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_SIGNED_UP = 'USER_SIGNED_UP';
export const USER_SIGNUP_FAILURE = 'USER_SIGNUP_FAILURE';
export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE';
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';
export const USER_LOGOUT_FAILURE = 'USER_LOGOUT_FAILURE';

export const RESOLVE_CLIENT = 'RESOLVE_CLIENT';
export const RESOLVE_SERVER = 'RESOLVE_SERVER';
export const OBJECTS_RESOLVED = 'OBJECT_RESOLVED';
export const RESET_OBJECTS_RESOLVED = 'RESET_OBJECTS_RESOLVED'
