export const LOAD_ABOUT_PAGE_DATA = 'LOAD_ABOUT_PAGE_DATA';
export const FETCH_ABOUT_PAGE_DATA = 'FETCH_ABOUT_PAGE_DATA';

export const USER_SIGNUP = 'USER_SIGNUP';
export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_SIGNED_UP = 'USER_SIGNED_UP';
export const USER_SIGNUP_FAILURE = 'USER_SIGNUP_FAILURE';
