export const LOAD_ABOUT_PAGE_DATA = 'LOAD_ABOUT_PAGE_DATA';
export const FETCH_ABOUT_PAGE_DATA = 'FETCH_ABOUT_PAGE_DATA';

export const USER_INIT = 'USER_INIT';
export const USER_SIGNUP = 'USER_SIGNUP';
export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_SIGNED_UP = 'USER_SIGNED_UP';
export const USER_SIGNUP_FAILURE = 'USER_SIGNUP_FAILURE';
export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE';
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';
export const USER_LOGOUT_FAILURE = 'USER_LOGOUT_FAILURE';

export const TODO_CREATE = 'TODO_CREATE';
export const TODO_CREATED = 'TODO_CREATED';
export const TODO_LIST_LOAD = 'TODO_LIST_LOAD';
export const TODO_LIST_LOADED = 'TODO_LIST_LOADED'
